
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./:/backend
    restart: always
    depends_on:
      - ollama
      - pgvector
    networks:
      - my-proxy-net
  
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    expose:
      - 11434
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - my-proxy-net

  pgvector:
    container_name: pgvector
    image: pgvector/pgvector:pg16
    expose:
      - 5432
    volumes:
      - ./pgvector:/var/lib/postgresql
    environment:
      POSTGRES_DB: langchain
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: bot-network
